### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by akorevaar** [F-Secure/mqtt_fuzz#2]
Hi, thanks for a great tool :). 
Is Python3 support something that others would like? I have implemented it here:

 *  https://github.com/akorevaar/mqtt_fuzz/commit/2c58ac42be3067a7152878dbb4686ae4938b14ef

I haven't spent any time trying to make this backward compatible with python2, and don't want to break what is already working for people. Please let me know if you'd like me to submit a pull request or have any suggestions on how to make it work for both.

**Comment by anttivs** [comment]
Sorry to be so slow with responding. To be honest, I think python2 compatibility can go at this stage as support is going to cease in the beginning of 2020. What if we'd just tag the current one as v1, get your pull request in and tag that v2. Or is there a more git-y way to do a breaking change?

The problem with me is that I have chronic lack of time and am probably not going to have that one spare evening for setting up a test environment.

**Comment by akorevaar** [comment]
All good. Tagging the current repo and optionally creating  a release for the python2 functionality sounds like a good way to go.
