### ISSUE TITLE
Does the Valid-cases include also MQTT Header?!

### ISSUE THREAD

**Issue by mohsenyaghoobi** [F-Secure/mqtt_fuzz#4]
Hi,
thanks a lot for your great tool :)
I want to know, if the valid-cases include also MQTT Header or they are just the payloads of MQTT packet?!
If they doesn't, where is built the header of MQTT it tool?!
I need your help as soon as possible, so I would be really thankful If you can answer me  :-)

Mohsen

**Comment by anttivs** [comment]
MQTT header is included, but the payload sizes are not recalculated for fuzz cases. If you would be fuzzing payload processing, you would need to rewrite the MQTT headers (correct length, etc.) so the payload gets through.
