### ISSUE TITLE
radamsa subprocess CalledProcessError error 

### ISSUE THREAD

**Issue by carlosjpr-collab** [F-Secure/mqtt_fuzz#8]
I am seeing this pb :
subprocess.CalledProcessError: Command '['/usr/bin/radamsa', '-o', '/tmp/tmpqv8b2mbu/%n.fuzz', '-n', '500', '-r', 'valid-cases/subscribe']' returned non-zero exit status 126.
radamsa is installed in my machine

**Comment by anttivs** [comment]
Exit status 126 means that the command is not executable. I am venturing a guess that your Radamsa binary lacks an execute permission.

**Comment by anttivs** [comment]
Likely not a bug in the script itself; closing as invalid.

**Comment by carlosjpr-collab** [comment]
The solution is to use radamsa 0.4 et not 0.6(last version)
